/*
  Proyecto Bases de Datos
  Entrega #3
  
  Integrantes:
    Arciniegas Rodolfo
    Guayara Cesar Alejandro
    Luis Caicedo
*/

DROP TABLE RENTA;
DROP TABLE ASESOR;
DROP TABLE LISTA_DE_VISITA;
DROP TABLE IMAGEN;
DROP TABLE PROPIEDAD;
DROP TABLE CIUDAD;
DROP TABLE COMPRADOR;
DROP TABLE PROPIETARIO;
DROP TABLE USUARIO;

CREATE TABLE USUARIO
(
  CEDULA NUMERIC(10,0) PRIMARY KEY,
  NOMBRE VARCHAR2(60),
  APELLIDO VARCHAR2(60),
  CORREO VARCHAR2(60)
);

CREATE TABLE PROPIETARIO
(
  IDP NUMERIC(3,0) PRIMARY KEY,
  CEDULA NUMERIC(10,0),
  USUARIO VARCHAR2(60),
  CONTRASENA VARCHAR2(60),
  FOREIGN KEY (CEDULA) REFERENCES USUARIO
);

CREATE TABLE COMPRADOR
(
    IDC NUMERIC(3,0) PRIMARY KEY,
    CEDULA NUMERIC(10,0),
    USUARIO VARCHAR2(60),
    CONTRASENA VARCHAR2(60),
    FOREIGN KEY (CEDULA) REFERENCES USUARIO
);

CREATE TABLE CIUDAD
(
  COD_CIUDAD NUMERIC(3,0) PRIMARY KEY,
  NOMBRE VARCHAR2(60)
);

CREATE TABLE PROPIEDAD
(
  ID_PROPIEDAD NUMERIC(3,0) PRIMARY KEY,
  TIPO VARCHAR2(60),
  NUM_HABITACIONES NUMERIC(2,0),
  COD_CIUDAD NUMERIC(3,0),
  DIRECCION VARCHAR2(60),
  ESTADO NUMERIC(1,0),
  IDP NUMERIC(3,0),
  IDC NUMERIC(3,0),
  FOREIGN KEY (COD_CIUDAD) REFERENCES CIUDAD,
  FOREIGN KEY (IDP) REFERENCES PROPIETARIO,
  FOREIGN KEY (IDC) REFERENCES COMPRADOR,
  CONSTRAINT CTIPO CHECK (UPPER(TIPO) IN ('APARTAMENTO','CASA'))
);

CREATE TABLE IMAGEN
(
  ID_PROPIEDAD NUMERIC(3,0),
  IMG CLOB,
  DESCRIPCION VARCHAR2(120),
  FECHA DATE,
  FOREIGN KEY (ID_PROPIEDAD) REFERENCES PROPIEDAD
);

CREATE TABLE LISTA_DE_VISITA
(
  ID_PROPIEDAD NUMERIC(3,0),
  IDC NUMERIC(3,0),
  FECHA DATE,
  FOREIGN KEY (ID_PROPIEDAD) REFERENCES PROPIEDAD,
  FOREIGN KEY (IDC) REFERENCES COMPRADOR,
  PRIMARY KEY (ID_PROPIEDAD, IDC)
);

CREATE TABLE ASESOR
(
  CEDULA NUMERIC(10,0) PRIMARY KEY,
  NOMBRE VARCHAR2(60),
  APELLIDO VARCHAR2(60),
  CORREO VARCHAR2(60)
);

CREATE TABLE RENTA
(
  IDC NUMERIC(3,0),
  IDPROP NUMERIC(3,0),
  ID_RENTA NUMERIC(3,0) PRIMARY KEY,
  FECHA_INICIO DATE,
  FECHA_FIN DATE,
  VALOR NUMERIC(10,0),
  CED_ASE NUMERIC(10,0),
  FOREIGN KEY (IDC) REFERENCES COMPRADOR,
  FOREIGN KEY (IDPROP) REFERENCES PROPIEDAD,
  FOREIGN KEY (CED_ASE) REFERENCES ASESOR
);