#pragma config(Sensor, S1,     sToque,         sensorTouch)
#pragma config(Sensor, S2,     sSonar,         sensorSONAR)
#pragma config(Sensor, S3,     sLuzDer,        sensorLightActive)
#pragma config(Sensor, S4,     sLuzIzq,        sensorLightActive)
#pragma config(Motor,  motorA,          mLuz,          tmotorNXT, PIDControl)
#pragma config(Motor,  motorB,          mDer,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mIzq,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Inicializacion de los motores y sensores

int verificarGrano()
{
	int resp;

	//Subida Sensores
	motor[motorA] = -25;
	wait1Msec(750);
	motor[motorA] = 0;
	wait1Msec(4000);
	
	//Verificacion Grano
	if(SensorValue[sLuzDer] > 45)
	{
		//Grano Inmaduro
		resp = 1;
	}
	else
	{
		//Grano Maduro
		resp = 0;
	}
	
	//Bajada Sensores
	motor[motorA] = 25;
	wait1Msec(680);

	return resp;
}

task main()
{
	//AVANCE HACIA DISPENSADOR
	while(SensorValue(sToque) == 0)
	{
		if(SensorValue[sLuzDer] < 39)
		{
			motor[motorC] = 150;
			motor[motorB] = -60;
			wait1Msec(65);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(65);
		}
		if(SensorValue[sLuzIzq] < 39)
		{
			motor[motorC] = -60;
			motor[motorB] = 150;
			wait1Msec(65);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(65);
		}
	}
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(500);
	//VERIFICACION GRANO
	int maduro = verificarGrano();
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(400);
	//RETROCESO
	motor[motorB] = -40;
	motor[motorC] = -40;
	wait1Msec(900);
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(400);
	//GIRO HACIA PROXIMA RUTA
	motor[motorC] = -60;
	motor[motorB] = 150;
	wait1Msec(750);
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(600);


	//AVANCE HACIA LAVADO
	while(SensorValue(sToque) == 0)
	{
		if(SensorValue[sLuzDer] < 39)
		{
			motor[motorC] = 150;
			motor[motorB] = -60;
			wait1Msec(45);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(45);
		}
		if(SensorValue[sLuzIzq] < 39)
		{
			motor[motorC] = -60;
			motor[motorB] = 150;
			wait1Msec(45);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(45);
		}
	}
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(400);
	//RETROCESO
	motor[motorB] = -20;
	motor[motorC] = -40;
	wait1Msec(1100);
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(400);
	//GIRO HACIA PROXIMA RUTA
	motor[motorC] = -60;
	motor[motorB] = 200;
	wait1Msec(500);
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(600);


	//AVANCE HACIA DISPENSADOR POS-LAVADO
	while(SensorValue(sToque) == 0)
	{
		if(SensorValue[sLuzDer] < 39)
		{
			motor[motorC] = 150;
			motor[motorB] = -60;
			wait1Msec(45);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(45);
		}
		if(SensorValue[sLuzIzq] < 39)
		{
			motor[motorC] = -60;
			motor[motorB] = 150;
			wait1Msec(45);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(45);
		}
	}
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(3000);
	//RETROCESO
	motor[motorB] = -20;
	motor[motorC] = -20;
	wait1Msec(1100);
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(400);
	//GIRO HACIA PROXIMA RUTA
	motor[motorC] = -60;
	motor[motorB] = 150;
	wait1Msec(850);
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(400);


	//AVANCE HACIA T
	while(SensorValue(sToque) == 0)
	{
		if(SensorValue[sLuzDer] < 39)
		{
			motor[motorC] = 150;
			motor[motorB] = -60;
			wait1Msec(45);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(45);
		}
		if(SensorValue[sLuzIzq] < 39)
		{
			motor[motorC] = -60;
			motor[motorB] = 150;
			wait1Msec(45);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(45);
		}
	}
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(600);
	//RETROCESO
	motor[motorB] = -20;
	motor[motorC] = -20;
	wait1Msec(1100);


	//CONDICIONAL MADURACION GRANO
	//ROJA PARA DERECHA
	if(maduro == 0)
	{
		//GIRO HACIA CANASTA
		motor[motorC] = 150;
		motor[motorB] = -60;
		wait1Msec(300);
		//FRENO
		motor[motorA] = 0;
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(400);
		//AVANCE HACIA CANASTA
		while(SensorValue(sToque) == 0)
		{
			if(SensorValue[sLuzDer] < 39)
			{
				motor[motorC] = 150;
				motor[motorB] = -60;
				wait1Msec(45);
			}
			else
			{
				motor[motorB] = 15;
				motor[motorC] = 15;
				wait1Msec(45);
			}
			if(SensorValue[sLuzIzq] < 39)
			{
				motor[motorC] = -60;
				motor[motorB] = 150;
				wait1Msec(45);
			}
			else
			{
				motor[motorB] = 15;
				motor[motorC] = 15;
				wait1Msec(45);
			}
		}
		//FRENO
		motor[motorA] = 0;
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(400);
		//GIRO DE 180 HACIA RUTA PARA DEVOLVERSE
		motor[motorC] = 150;
		motor[motorB] = -60;
		wait1Msec(1000);
		//FRENO
		motor[motorA] = 0;
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(600);
		//AVANCE HACIA RUTA
		while(SensorValue(sToque) == 0)
		{
			if(SensorValue[sLuzDer] < 39)
			{
				motor[motorC] = 150;
				motor[motorB] = -60;
				wait1Msec(45);
			}
			else
			{
				motor[motorB] = 15;
				motor[motorC] = 15;
				wait1Msec(45);
			}
			if(SensorValue[sLuzIzq] < 39)
			{
				motor[motorC] = -60;
				motor[motorB] = 150;
				wait1Msec(45);
			}
			else
			{
				motor[motorB] = 15;
				motor[motorC] = 15;
				wait1Msec(45);
			}
		}
		//FRENO
		motor[motorA] = 0;
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(400);
		//GIRO HACIA RUTA
		motor[motorC] = -60;
		motor[motorB] = 150;
		wait1Msec(500);
	}

	//AZUL PARA IZQUIERDA
	else
	{
		//GIRO HACIA CANASTA
		motor[motorC] = -60;
		motor[motorB] = 150;
		wait1Msec(300);
		//FRENO
		motor[motorA] = 0;
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(400);
		//AVANCE HACIA CANASTA
		while(SensorValue(sToque) == 0)
		{
			if(SensorValue[sLuzDer] < 39)
			{
				motor[motorC] = 150;
				motor[motorB] = -60;
				wait1Msec(45);
			}
			else
			{
				motor[motorB] = 15;
				motor[motorC] = 15;
				wait1Msec(45);
			}
			if(SensorValue[sLuzIzq] < 39)
			{
				motor[motorC] = -60;
				motor[motorB] = 150;
				wait1Msec(45);
			}
			else
			{
				motor[motorB] = 15;
				motor[motorC] = 15;
				wait1Msec(45);
			}
		}
		//FRENO
		motor[motorA] = 0;
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(400);
		//GIRO DE 180 HACIA RUTA PARA DEVOLVERSE
		motor[motorC] = 150;
		motor[motorB] = -60;
		wait1Msec(1000);
		//FRENO
		motor[motorA] = 0;
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(400);
		//AVANCE HACIA RUTA
		while(SensorValue(sToque) == 0)
		{
			if(SensorValue[sLuzDer] < 39)
			{
				motor[motorC] = 150;
				motor[motorB] = -60;
				wait1Msec(45);
			}
			else
			{
				motor[motorB] = 15;
				motor[motorC] = 15;
				wait1Msec(45);
			}
			if(SensorValue[sLuzIzq] < 39)
			{
				motor[motorC] = -60;
				motor[motorB] = 150;
				wait1Msec(45);
			}
			else
			{
				motor[motorB] = 15;
				motor[motorC] = 15;
				wait1Msec(45);
			}
		}
		//FRENO
		motor[motorA] = 0;
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(400);
		//GIRO HACIA RUTA
		motor[motorC] = 150;
		motor[motorB] = -60;
		wait1Msec(500);
	}


	//AVANCE HACIA U
	while(SensorValue(sToque) == 0)
	{
		if(SensorValue[sLuzDer] < 39)
		{
			motor[motorC] = 150;
			motor[motorB] = -60;
			wait1Msec(45);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(45);
		}
		if(SensorValue[sLuzIzq] < 39)
		{
			motor[motorC] = -60;
			motor[motorB] = 150;
			wait1Msec(45);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(45);
		}
	}
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(400);
	//GIRO HACIA PROXIMA RUTA
	motor[motorC] = 150;
	motor[motorB] = -60;
	wait1Msec(800);
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(400);


	//AVANCE HACIA RUTA PRINCIPAL
	while(SensorValue(sToque) == 0)
	{
		if(SensorValue[sLuzDer] < 39)
		{
			motor[motorC] = 150;
			motor[motorB] = -60;
			wait1Msec(45);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(45);
		}
		if(SensorValue[sLuzIzq] < 39)
		{
			motor[motorC] = -60;
			motor[motorB] = 150;
			wait1Msec(45);
		}
		else
		{
			motor[motorB] = 15;
			motor[motorC] = 15;
			wait1Msec(45);
		}
	}
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(400);
	//GIRO HACIA PROXIMA RUTA
	motor[motorC] = 150;
	motor[motorB] = -60;
	wait1Msec(800);
	//FRENO
	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait1Msec(400);
}
